# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      CPLUS_INCLUDE_PATH: "/usr/local/include/:/usr/include/jsoncpp/:/usr/lib/"
    steps:
      - uses: actions/checkout@v2

      - name: Update dependencies
        run: |
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt-get update
          sudo apt-get remove g++ g++-10
          sudo apt-get install gcc-10 g++-10
          sudo rm -rf /usr/bin/gcc
          sudo ln -sf /usr/bin/gcc-10 /usr/bin/gcc
      
      - name: Install dependencies
        run: |
          sudo apt-get install git libboost-all-dev 
          sudo apt-get install lcov libcpprest-dev libssl-dev uuid-dev libjson-c-dev libjsoncpp-dev --fix-missing
          sudo apt-get install libcurl4-openssl-dev
      
      - name: Build facebody c++ sdk
        run: |
          git clone https://github.com/alibabacloud-sdk-cpp/facebody-20191230.git
          cd facebody-20191230 && rm -rf cmake_build/
          sh scripts/build.sh

      - name: Save build result
        run: |
          echo $PWD
          rm -rf cmake_build/_deps/
          git add ./cmake_build -f
          git commit -m "Build facebody-20191230 C++ SDK"
          git checkout -b build/facabody-cpp-sdk
          git config --local user.email "axioscros@aliyun.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push --force --set-upstream origin build/facabody-cpp-sdk
